import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export const metadata = {
  title: "Terms of Service — WatchSnap",
  description: "WatchSnap Terms of Service — the rules governing use of the WatchSnap platform.",
  openGraph: {
    title: "Terms of Service — WatchSnap",
    description: "WatchSnap Terms of Service — the rules governing use of the WatchSnap platform.",
    url: "https://watchsnap.vercel.app/terms",
    siteName: "WatchSnap",
    images: [{ url: "https://watchsnap.vercel.app/icons/icon-512.png", width: 512, height: 512 }],
  },
  twitter: { card: "summary", title: "Terms of Service — WatchSnap" },
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#0A0A0A] text-white">
      <div className="mx-auto max-w-3xl px-4 pt-20 pb-10">
        <Link href="/landing" className="mb-6 inline-flex items-center gap-1.5 text-sm text-gray-500 hover:text-white transition-colors">
          <ArrowLeft className="h-4 w-4" /> Back to Home
        </Link>
        {/* Header */}
        <div className="mb-12 border-b border-[#1E1E1E] pb-8">
          <p className="text-xs font-bold uppercase tracking-widest text-[#C9A84C] mb-3">Legal</p>
          <h1 className="text-4xl font-black sm:text-5xl mb-4">Terms of Service</h1>
          <p className="text-gray-500 text-sm">Last updated: May 11, 2026</p>
        </div>

        <div className="prose-legal">
          <Section title="1. Acceptance of Terms">
            <p>
              By accessing or using WatchSnap (&quot;the Service&quot;, &quot;the App&quot;), you agree to be bound by these Terms of Service
              and all applicable laws. If you do not agree with any of these terms, you are prohibited from using the Service.
              These Terms apply to all visitors, users, and others who access or use the Service.
            </p>
          </Section>

          <Section title="2. Description of Service">
            <p>
              WatchSnap is an AI-powered web application that provides watch identification, market valuation estimates,
              and authentication analysis based on photographs submitted by users. The Service is provided &quot;as is&quot; and
              is intended for informational and reference purposes only.
            </p>
            <p>
              <strong>WatchSnap is not a certified appraiser, authenticator, or dealer.</strong> Results generated by the Service
              are AI estimates and should not be treated as professional appraisals, certified authentication, or financial advice.
              Always consult a qualified horological expert before making significant purchase, sale, or insurance decisions.
            </p>
          </Section>

          <Section title="3. User Accounts and Registration">
            <p>
              Basic use of WatchSnap (up to 3 free scans) does not require registration. A paid subscription unlocks
              unlimited scans. You are responsible for maintaining the confidentiality of your account credentials
              and for all activities that occur under your account.
            </p>
          </Section>

          <Section title="4. Subscriptions and Payments">
            <SubHeading>4.1 Subscription Plans</SubHeading>
            <p>
              WatchSnap offers monthly and annual subscription plans. Pricing is displayed on the pricing page and
              at checkout. All prices are in USD and subject to applicable taxes.
            </p>

            <SubHeading>4.2 Free Trial</SubHeading>
            <p>
              Monthly subscriptions include a 7-day free trial. During the trial, your payment method is saved but
              not charged. After the trial period, your subscription begins automatically. You may cancel before
              the trial ends to avoid any charge.
            </p>

            <SubHeading>4.3 Billing</SubHeading>
            <p>
              Payments are processed by <strong>Link, LLC f/k/a Lemon Squeezy LLC (&quot;Lemon Squeezy&quot;)</strong>,
              our Merchant of Record. By subscribing you authorise Lemon Squeezy to charge your payment method on a
              recurring basis (monthly or annually) until you cancel. Lemon Squeezy issues all receipts and invoices
              and is responsible for payment processing, refunds, and tax remittance on your behalf.
            </p>

            <SubHeading>4.4 Cancellation</SubHeading>
            <p>
              You may cancel your subscription at any time through your Lemon Squeezy customer portal or by contacting
              us. Cancellation takes effect at the end of the current billing period; you retain access until then.
            </p>
          </Section>

          <Section title="5. Refunds">
            <p>
              Please refer to our <Link href="/refund" className="text-[#C9A84C] hover:underline">Refund Policy</Link> for full details.
              In summary, annual subscribers are eligible for a full refund within 30 days of purchase if unsatisfied.
              Monthly subscribers may request a refund within 7 days of their first charge (after the free trial).
            </p>
          </Section>

          <Section title="6. Acceptable Use">
            <p>You agree not to:</p>
            <ul>
              <li>Use the Service for any unlawful purpose or in violation of any laws</li>
              <li>Attempt to reverse-engineer, decompile, or extract the Service&apos;s AI models or source code</li>
              <li>Submit content that is illegal, harmful, threatening, abusive, or infringes intellectual property rights</li>
              <li>Use automated scripts, bots, or other tools to access the Service in bulk</li>
              <li>Attempt to circumvent rate limits, paywalls, or access controls</li>
              <li>Resell, sublicense, or commercially exploit the Service without written permission</li>
              <li>Impersonate any person or entity or misrepresent your affiliation</li>
            </ul>
          </Section>

          <Section title="7. Intellectual Property">
            <p>
              The WatchSnap name, logo, design, software, and AI models are the exclusive property of WatchSnap and
              are protected by copyright, trademark, and other intellectual property laws. You are granted a limited,
              non-exclusive, non-transferable licence to use the Service for personal, non-commercial purposes.
            </p>
            <p>
              You retain ownership of images you submit. By submitting images you grant WatchSnap a limited licence
              to process those images solely for the purpose of providing the identification Service.
            </p>
          </Section>

          <Section title="8. Disclaimer of Warranties">
            <p>
              THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED,
              INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.
            </p>
            <p>
              WatchSnap does not warrant that: (a) the Service will be uninterrupted or error-free; (b) AI identification
              results will be 100% accurate; (c) market valuations represent actual transaction prices; or (d) authentication
              verdicts constitute professional certification.
            </p>
          </Section>

          <Section title="9. Limitation of Liability">
            <p>
              TO THE FULLEST EXTENT PERMITTED BY LAW, WATCHSNAP SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL,
              SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS, DATA, GOODWILL, OR OTHER
              INTANGIBLE LOSSES, ARISING FROM YOUR USE OF OR INABILITY TO USE THE SERVICE.
            </p>
            <p>
              IN NO EVENT SHALL OUR TOTAL LIABILITY TO YOU EXCEED THE AMOUNT YOU PAID FOR THE SERVICE IN THE
              TWELVE MONTHS PRECEDING THE CLAIM.
            </p>
          </Section>

          <Section title="10. Accuracy Disclaimer">
            <p>
              WatchSnap uses AI technology to provide watch authentication and valuation estimates.
              Results are for informational purposes only and may not be 100% accurate.
              WatchSnap is not liable for any decisions made based on scan results.
              Always consult a professional authenticator before making significant purchasing decisions.
            </p>
          </Section>

          <Section title="11. Privacy">
            <p>
              Your use of the Service is also governed by our{" "}
              <Link href="/privacy" className="text-[#C9A84C] hover:underline">Privacy Policy</Link>,
              which is incorporated into these Terms by reference.
            </p>
          </Section>

          <Section title="12. Modifications to the Service">
            <p>
              WatchSnap reserves the right to modify, suspend, or discontinue the Service (or any part of it) at any time
              with or without notice. We are not liable to you or any third party for any modification, suspension, or discontinuation.
            </p>
          </Section>

          <Section title="13. Changes to Terms">
            <p>
              We reserve the right to update these Terms at any time. We will indicate the date of the last revision above.
              Continued use of the Service after changes constitutes your acceptance of the new Terms.
            </p>
          </Section>

          <Section title="14. Governing Law">
            <p>
              These Terms shall be governed by and construed in accordance with applicable law. Any disputes arising
              from these Terms or your use of the Service shall be resolved through good-faith negotiation first,
              and thereafter through binding arbitration or competent courts as required by applicable law.
            </p>
          </Section>

          <Section title="15. Contact">
            <p>Questions about these Terms? Contact us at:</p>
            <div className="mt-3 rounded-2xl border border-[#1E1E1E] bg-[#111111] p-5">
              <p className="font-bold text-white">WatchSnap</p>
              <p className="text-gray-400 mt-1">Email: <a href="mailto:watchsnapapp@gmail.com" className="text-[#C9A84C] hover:underline">watchsnapapp@gmail.com</a></p>
            </div>
          </Section>
        </div>

      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mb-10">
      <h2 className="mb-4 text-xl font-black text-white">{title}</h2>
      <div className="space-y-3 text-gray-400 leading-relaxed text-sm [&_strong]:text-gray-200 [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:space-y-1.5 [&_a]:text-[#C9A84C]">
        {children}
      </div>
    </div>
  );
}

function SubHeading({ children }: { children: React.ReactNode }) {
  return <h3 className="mt-5 mb-2 font-bold text-gray-200 text-base">{children}</h3>;
}
